version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./db:/var/lib/postgresql/data/
    env_file:
      - ../museum_news/.env
  web:
    image: mvrogozov/museum_news:v0.0.1
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    env_file:
      - ../museum_news/.env

  celery:
    image: mvrogozov/museum_news:v0.0.1
    command: celery --app=museum_news worker --pool=solo --loglevel=info
    env_file:
      - ../museum_news/.env
    depends_on:
      - web
      - redis

  redis:
    image: redis:5-alpine
