# Generated by Django 4.1.5 on 2023-02-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128, verbose_name='Адрес сайта')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('news', models.TextField(max_length=10000, verbose_name='Новость')),
            ],
        ),
    ]
